name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        vim_version:
          - head
          - v9.0.0000
          - v8.2.0000
          - v8.1.0001
          - v8.0.0002
        arch:
          - x86
          - x86_64
      fail-fast: false
    name: Vim ${{ matrix.vim_version }} (${{ matrix.arch }})
    runs-on: windows-latest
    env:
      PROFILE: profile.txt
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout themis.vim
        uses: actions/checkout@v4
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v1
        with:
          vim_version: ${{ matrix.vim_version }}
          arch: ${{ matrix.arch }}
          download: always
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install covimerage
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -U covimerage
      - name: Test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis --reporter spec
      - name: Generate XML coverage report
        run: |
          covimerage write_coverage ${{ env.PROFILE }}
          covimerage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
