name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        vim_version:
          - head
          - v9.1.0000
          - v9.0.0000
          - v8.2.0000
          - v8.1.0001
          - v8.0.0002
        arch:
          - x86
          - x86_64
      fail-fast: false
    name: Vim ${{ matrix.vim_version }} (${{ matrix.arch }})
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout themis.vim
        uses: actions/checkout@v4
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v2
        with:
          vim_version: ${{ matrix.vim_version }}
          arch: ${{ matrix.arch }}
          download: always
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Primula
        run: |
          python -m pip install -U pip
          python -m pip install -U primula
      - name: Test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          primula run ./vim-themis/bin/themis --reporter spec
          primula report -m
      - name: Generate XML coverage report
        run: primula xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          plugins: noop
